/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Javaproject1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
           int billingDate = 5;
        System.out.println("Bills are senton the ");
        System.out.println(billingDate +"th");
        System.out.println("day");
        System.out.println("of the month");
        System.out.println("Next bill:October"+ billingDate);
    }
}
